/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package quanlyphonggym.UI.AdminUI.QuanLyHoiVienUI;

import quanlyphonggym.Controllers.AdminCtrl.QuanLyNhanVienCtrl.DanhSachHoiVienCtrl;
import quanlyphonggym.Models.HoiVien;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;
import java.sql.SQLException;
import java.util.EventObject;
import java.util.List;

/**
 *
 * @author nguyenduc
 */
public class QuanLyHoiVienPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyHoiVienPanel
     */
    public QuanLyHoiVienPanel() throws SQLException, ClassNotFoundException {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableDanhSachHoiVien = new javax.swing.JTable();
        jLabelDanhSachHoiVien = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTableDanhSachHoiVien.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jTableDanhSachHoiVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
                new String [] {
                        "ID", "Mã HV", "Họ tên", "Ngày sinh", "Giới tính", "Loại thành viên"
                }
        ));
        danhSachHoiVien = (DefaultTableModel) jTableDanhSachHoiVien.getModel();
        TableCellEditor nonEditableCellEditor = new DefaultCellEditor(new JTextField()) {
            @Override
            public boolean isCellEditable(EventObject e) {
                return false;
            }
        };
        for (int column = 0; column < danhSachHoiVien.getColumnCount(); column++) {
            TableColumn tableColumn = jTableDanhSachHoiVien.getColumnModel().getColumn(column);
            tableColumn.setCellEditor(nonEditableCellEditor);
        }
        jTableDanhSachHoiVien.setToolTipText("");
        jTableDanhSachHoiVien.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableDanhSachHoiVien.setFocusable(false);
        jTableDanhSachHoiVien.setRowHeight(30);
        jTableDanhSachHoiVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    jTableDanhSachHoiVienMouseClicked(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTableDanhSachHoiVienMouseEntered(evt);
            }
        });
        jTableDanhSachHoiVien.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableDanhSachHoiVienKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableDanhSachHoiVien);

        jLabelDanhSachHoiVien.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDanhSachHoiVien.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabelDanhSachHoiVien.setText("Danh sách hội viên:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelDanhSachHoiVien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(202, 202, 202))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabelDanhSachHoiVien)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1079, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 641, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    private void loadData() throws SQLException, ClassNotFoundException {
        if (danhSachHoiVien.getRowCount()>0) danhSachHoiVien.setRowCount(0);
        DanhSachHoiVienCtrl danhSachHoiVienCtrl = new DanhSachHoiVienCtrl();
        List<HoiVien> hoiViens = danhSachHoiVienCtrl.getAllHoiVien();
        for (int i = 0; i < hoiViens.size(); i++) {
            int idHocVien = hoiViens.get(i).getId();
            String maHV = hoiViens.get(i).getMaHoiVien();
            String hoTen = hoiViens.get(i).getHoTen();
            String ngaySinh = hoiViens.get(i).getNgaySinh();
            String gioTinh = hoiViens.get(i).getGioiTinh();
            String loaiThanhVien = hoiViens.get(i).getLoaiThanhVien();
            Object[] row = {idHocVien, maHV, hoTen, ngaySinh, gioTinh, loaiThanhVien};
            danhSachHoiVien.addRow(row);
        }

    }
    private void jTableDanhSachHoiVienMouseClicked(java.awt.event.MouseEvent evt) throws SQLException, ClassNotFoundException {//GEN-FIRST:event_jTableDanhSachHoiVienMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount()==2) {
            int row = jTableDanhSachHoiVien.getSelectedRow();
            int idHoiVien = (int) jTableDanhSachHoiVien.getValueAt(row, 0);
            ThongTinChiTietHoiVienJframe thongTinChiTietHoiVienJframe = new ThongTinChiTietHoiVienJframe (idHoiVien);
            thongTinChiTietHoiVienJframe.setVisible(true);
        }
    }//GEN-LAST:event_jTableDanhSachHoiVienMouseClicked

    private void jTableDanhSachHoiVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDanhSachHoiVienMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableDanhSachHoiVienMouseEntered

    private void jTableDanhSachHoiVienKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableDanhSachHoiVienKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableDanhSachHoiVienKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelDanhSachHoiVien;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableDanhSachHoiVien;
    // End of variables declaration//GEN-END:variables
    private DefaultTableModel danhSachHoiVien;
}
