/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlyphonggym.UI.AdminUI.QuanLyHoiVienUI;

import quanlyphonggym.Bean.DangKyGoiTapBean;
import quanlyphonggym.Bean.HoiVienBean;
import quanlyphonggym.Bean.PhanHoiBean;
import quanlyphonggym.Controllers.AdminCtrl.QuanLyHoiVienCtrl.ChiTietHoiVienCtrl;
import quanlyphonggym.Models.*;
import quanlyphonggym.UI.AdminUI.QuanLyGoiTapUI.PhanHoiJframe;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;
import java.sql.SQLException;
import java.util.EventObject;
import java.util.List;

/**
 *
 * @author nguyenduc
 */
public class ThongTinChiTietHoiVienJframe extends javax.swing.JFrame {

    /**
     * Creates new form ThongTinChiTietHoiVienJframe
     */

    public ThongTinChiTietHoiVienJframe(int idHoiVien) throws SQLException, ClassNotFoundException {
        this.idHoiVien = idHoiVien;
        initComponents();
        setLocationRelativeTo(null);
        loadData();
        jTextIdHocVien.setEditable(false);
        jTextMaHocVien.setEditable(false);
        jTextHoTen.setEditable(false);
        jTextNgaySinh.setEditable(false);
        jTextGioiTinh.setEditable(false);
        jTextDiaChi.setEditable(false);
        jTextSoDienThoai.setEditable(false);
        jTextLoaiThanhVien.setEditable(false);
        jTextGoiTapHienTai.setEditable(false);
        jTextNgayDangKy.setEditable(false);
        jTextNgayBatDau.setEditable(false);
        jTextNgayKetThuc.setEditable(false);
        jTextPTHuongDan.setEditable(false);
        jTextMaNhanVienPT.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextIdHocVien = new javax.swing.JTextField();
        jTextMaHocVien = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextHoTen = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextNgaySinh = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextGioiTinh = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextDiaChi = new javax.swing.JTextField();
        jTextSoDienThoai = new javax.swing.JTextField();
        jTextLoaiThanhVien = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextGoiTapHienTai = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableLichSu = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCacGoi = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jTextNgayDangKy = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextNgayBatDau = new javax.swing.JTextField();
        jTextNgayKetThuc = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTextPTHuongDan = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTablePhanHoi = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextMaNhanVienPT = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thông tin chi tiết hội viên");

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setEnabled(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setText("ID Học viên:");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel4.setText("Mã Học viên:");

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel5.setText("Họ tên:");

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel6.setText("Ngày sinh:");

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel7.setText("Giới tính:");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel2.setText("Địa chỉ:");

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel8.setText("Số điện thoại:");

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel9.setText("Loại thành viên:");

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel10.setText("Gói tập hiện tại:");

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setText("Lịch sử sử dụng phòng tập:");

        jTableLichSu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Giờ vào", "Giờ ra", "Ngày tập luyện"
            }
        ));
        danhSachLichSu = (DefaultTableModel) jTableLichSu.getModel();
        TableCellEditor nonEditableCellEditor1 = new DefaultCellEditor(new JTextField()) {
            @Override
            public boolean isCellEditable(EventObject e) {
                return false;
            }
        };
        for (int column = 0; column < danhSachLichSu.getColumnCount(); column++) {
            TableColumn tableColumn = jTableLichSu.getColumnModel().getColumn(column);
            tableColumn.setCellEditor(nonEditableCellEditor1);
        }
        jTableLichSu.setRowHeight(30);
        jScrollPane2.setViewportView(jTableLichSu);

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel11.setText("Các gói tập đã đăng ký:");

        jTableCacGoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên gói", "Ngày đăng kí", "Ngày bắt đầu", "Ngày kết thúc"
            }
        ));
        danhSachCacGoi = (DefaultTableModel) jTableCacGoi.getModel();
        TableCellEditor nonEditableCellEditor2 = new DefaultCellEditor(new JTextField()) {
            @Override
            public boolean isCellEditable(EventObject e) {
                return false;
            }
        };
        for (int column = 0; column < danhSachCacGoi.getColumnCount(); column++) {
            TableColumn tableColumn = jTableCacGoi.getColumnModel().getColumn(column);
            tableColumn.setCellEditor(nonEditableCellEditor2);
        }
        jTableCacGoi.setRowHeight(30);
        jTableCacGoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCacGoiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTableCacGoiMouseEntered(evt);
            }
        });
        jScrollPane3.setViewportView(jTableCacGoi);

        jLabel12.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel12.setText("Ngày đăng ký:");

        jLabel13.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel13.setText("Ngày bắt đầu:");

        jLabel14.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel14.setText("Ngày kết thúc:");

        jLabel15.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel15.setText("PT Hướng dẫn:");

        jTablePhanHoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ID Nhân viên", "Ý kiến hội viên", "Trả lời", "Check", "Ngày phản hồi"
            }
        ));

        danhSachPhanHoi = (DefaultTableModel) jTablePhanHoi.getModel();
        TableCellEditor nonEditableCellEditor3 = new DefaultCellEditor(new JTextField()) {
            @Override
            public boolean isCellEditable(EventObject e) {
                return false;
            }
        };
        for (int column = 0; column < danhSachPhanHoi.getColumnCount(); column++) {
            TableColumn tableColumn = jTablePhanHoi.getColumnModel().getColumn(column);
            tableColumn.setCellEditor(nonEditableCellEditor3);
        }
        jTablePhanHoi.setRowHeight(30);
        jTablePhanHoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                try {
                    jTablePhanHoiMouseClicked(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
        });
        jScrollPane4.setViewportView(jTablePhanHoi);

        jLabel16.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel16.setText("Danh sách ý kiến phải hồi của Hội viên:");

        jLabel17.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel17.setText("Mã nhân viên PT:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jScrollPane3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(103, 103, 103))
                            .addComponent(jSeparator1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextLoaiThanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(51, 51, 51)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(59, 59, 59)
                                        .addComponent(jTextMaNhanVienPT, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextNgaySinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextHoTen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextIdHocVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextMaHocVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(51, 51, 51)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(59, 59, 59)
                                                .addComponent(jTextGoiTapHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGap(59, 59, 59)
                                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jTextNgayDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jTextNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGap(59, 59, 59)
                                                    .addComponent(jTextNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGap(59, 59, 59)
                                                    .addComponent(jTextPTHuongDan, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                            .addComponent(jScrollPane4))
                        .addGap(47, 47, 47))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextGoiTapHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNgayDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextPTHuongDan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextMaNhanVienPT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextIdHocVien, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextMaHocVien, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextLoaiThanhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(33, 33, 33)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 907, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTableCacGoiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCacGoiMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableCacGoiMouseEntered

    private void jTableCacGoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCacGoiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableCacGoiMouseClicked


    private void jTablePhanHoiMouseClicked(java.awt.event.MouseEvent evt) throws SQLException, ClassNotFoundException {//GEN-FIRST:event_jTableCacGoiMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 ) {
            PhanHoiBean phanHoiBean = new PhanHoiBean();
            PhanHoiCuaHoiVien phanHoiCuaHoiVien = new PhanHoiCuaHoiVien();
            PhanHoiCuaAdmin phanHoiCuaAdmin = new PhanHoiCuaAdmin();

            int row = jTablePhanHoi.getSelectedRow();
            int id = (int) jTablePhanHoi.getValueAt(row, 0);

            PhanHoiJframe phanHoiJframe = new PhanHoiJframe(id);
            phanHoiJframe.setVisible(true);
        }
    }//GEN-LAST:event_jTableCacGoiMouseClicked

    public static void loadData() throws SQLException, ClassNotFoundException {
        ChiTietHoiVienCtrl chiTietHoiVienCtrl = new ChiTietHoiVienCtrl();
        HoiVienBean hoiVienBean = chiTietHoiVienCtrl.getChiTietHoiVienById(idHoiVien);

        HoiVien hoiVien = hoiVienBean.getHoiVien();
        DangKyGoiTapBean goiTapHienTai = hoiVienBean.getGoiTapHienTai();
        List<DangKyGoiTapBean> danhSachGoiTapDaDangKy = hoiVienBean.getDanhSachGoiTapDaDangKy();
        List<LichSu> lichSuSuDungDichVu = hoiVienBean.getLichSuSuDungDichVu();
        List<PhanHoiBean> danhSachPhanHoiHoiVien = hoiVienBean.getDanhSachPhanHoi();
        NhanVien PT = hoiVienBean.getPT(); //người hướng dẫn

        jTextIdHocVien.setText(String.valueOf(hoiVien.getId()));
        jTextMaHocVien.setText(hoiVien.getMaHoiVien());
        jTextHoTen.setText(hoiVien.getHoTen());
        jTextNgaySinh.setText(hoiVien.getNgaySinh());
        jTextGioiTinh.setText(hoiVien.getGioiTinh());
        jTextDiaChi.setText(hoiVien.getDiaChi());
        jTextSoDienThoai.setText(hoiVien.getSoDienThoai());
        jTextLoaiThanhVien.setText(hoiVien.getLoaiThanhVien());

        if (goiTapHienTai.getGoiTap() != null) {

            jTextGoiTapHienTai.setText(goiTapHienTai.getGoiTap().getTenGoiTap());
            jTextNgayDangKy.setText(goiTapHienTai.getDangKyGoiTap().getNgayDangKy());
            jTextNgayBatDau.setText(goiTapHienTai.getDangKyGoiTap().getNgayBatDau());
            jTextNgayKetThuc.setText(goiTapHienTai.getDangKyGoiTap().getNgayKetThuc());
            jTextPTHuongDan.setText(PT.getHoTen());
            jTextMaNhanVienPT.setText(PT.getMaNhanVien());
        } else {
            jTextGoiTapHienTai.setText("Hội viên chưa đăng ký gói nào");
        }

        if (danhSachLichSu.getRowCount()>0) danhSachLichSu.setRowCount(0);
        for (int i = 0; i<lichSuSuDungDichVu.size(); i++) {
            String gioVao = lichSuSuDungDichVu.get(i).getGioVao();
            String gioRa = lichSuSuDungDichVu.get(i).getGioRa();
            String ngayTapLuyen = lichSuSuDungDichVu.get(i).getNgaySuDung();

            Object[] row = {gioVao, gioRa, ngayTapLuyen};
            danhSachLichSu.addRow(row);
        }

        if (danhSachCacGoi.getRowCount()>0) danhSachCacGoi.setRowCount(0);
        for (int i = 0; i<danhSachGoiTapDaDangKy.size(); i++) {
            String tenGoi = danhSachGoiTapDaDangKy.get(i).getGoiTap().getTenGoiTap();
            String ngayDangKy = danhSachGoiTapDaDangKy.get(i).getDangKyGoiTap().getNgayDangKy();
            String ngayBatDau = danhSachGoiTapDaDangKy.get(i).getDangKyGoiTap().getNgayBatDau();
            String ngayKetThuc = danhSachGoiTapDaDangKy.get(i).getDangKyGoiTap().getNgayKetThuc();

            Object[] row = {tenGoi, ngayDangKy, ngayBatDau, ngayKetThuc};
            danhSachCacGoi.addRow(row);
        }

        if (danhSachPhanHoi.getRowCount()>0) danhSachPhanHoi.setRowCount(0);
        for (int i = 0; i<danhSachPhanHoiHoiVien.size(); i++) {
            int id = danhSachPhanHoiHoiVien.get(i).getPhanHoiCuaHoiVien().getId();
            int idNhanVien = danhSachPhanHoiHoiVien.get(i).getPhanHoiCuaHoiVien().getIdNhanVien();
            String yKienHoiVien = danhSachPhanHoiHoiVien.get(i).getPhanHoiCuaHoiVien().getNoiDung();
            String traLoi = null;
            String check = "Chưa trả lời";
            String ngayPhanHoi = danhSachPhanHoiHoiVien.get(i).getPhanHoiCuaHoiVien().getNgayPhanHoi();

            if (danhSachPhanHoiHoiVien.get(i).getPhanHoiCuaHoiVien().getIsDaPhanHoiLai()) {
                traLoi = danhSachPhanHoiHoiVien.get(i).getPhanHoiCuaAdmin().getNoiDung();
                check = "đã trả lời";
            }

            Object[] row = {id, idNhanVien, yKienHoiVien, traLoi, check, ngayPhanHoi};
            danhSachPhanHoi.addRow(row);
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTableCacGoi;
    private javax.swing.JTable jTableLichSu;
    private javax.swing.JTable jTablePhanHoi;
    private static javax.swing.JTextField jTextDiaChi;
    private static javax.swing.JTextField jTextGioiTinh;
    private static javax.swing.JTextField jTextGoiTapHienTai;
    private static javax.swing.JTextField jTextHoTen;
    private static javax.swing.JTextField jTextIdHocVien;
    private static javax.swing.JTextField jTextLoaiThanhVien;
    private static javax.swing.JTextField jTextMaHocVien;
    private static javax.swing.JTextField jTextMaNhanVienPT;
    private static javax.swing.JTextField jTextNgayBatDau;
    private static javax.swing.JTextField jTextNgayDangKy;
    private static javax.swing.JTextField jTextNgayKetThuc;
    private static javax.swing.JTextField jTextNgaySinh;
    private static javax.swing.JTextField jTextPTHuongDan;
    private static javax.swing.JTextField jTextSoDienThoai;
    // End of variables declaration//GEN-END:variables
    private static DefaultTableModel danhSachLichSu;
    private static DefaultTableModel danhSachPhanHoi;
    private static DefaultTableModel danhSachCacGoi;
    private static int idHoiVien;
}
