/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package quanlyphonggym.UI.AdminUI.QuanLyGoiTapUI;

/**
 *
 * @author nguyenduc
 */
public class QuanLyGoiTapPanel extends javax.swing.JPanel {

    /**
     * Creates new form QuanLyGoiTapPanel
     */
    public QuanLyGoiTapPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableGoiTap = new javax.swing.JTable();
        jButtonThemNhanVien = new javax.swing.JButton();
        jButtonSuaNhanVien = new javax.swing.JButton();
        jButtonXoaNhanVien = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jTableGoiTap.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jTableGoiTap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"fdds", "dsfgsd", "df", null},
                {null, null, null, null},
                {null, "dfdf", null, null},
                {null, "dfdf", null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTableGoiTap.setToolTipText("");
        jTableGoiTap.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableGoiTap.setFocusable(false);
        jTableGoiTap.setRowHeight(30);
        jTableGoiTap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableGoiTapMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTableGoiTapMouseEntered(evt);
            }
        });
        jTableGoiTap.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTableGoiTapKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTableGoiTap);

        jButtonThemNhanVien.setBackground(new java.awt.Color(255, 255, 153));
        jButtonThemNhanVien.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jButtonThemNhanVien.setText("Thêm gói tập");
        jButtonThemNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThemNhanVienActionPerformed(evt);
            }
        });

        jButtonSuaNhanVien.setBackground(new java.awt.Color(255, 255, 153));
        jButtonSuaNhanVien.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jButtonSuaNhanVien.setText("Sửa Gói tập");
        jButtonSuaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSuaNhanVienActionPerformed(evt);
            }
        });

        jButtonXoaNhanVien.setBackground(new java.awt.Color(255, 255, 153));
        jButtonXoaNhanVien.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jButtonXoaNhanVien.setText("Xóa Gói tập");
        jButtonXoaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonXoaNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 751, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSuaNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonThemNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(jButtonXoaNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonThemNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSuaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonXoaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableGoiTapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGoiTapMouseClicked
        // TODO add your handling code here:
        //        if (evt.getClickCount()==2) {
            //            int row = jTableNhanVien.getSelectedRow();
            //            int IdNhanKhau = (int) jTableNhanVien.getValueAt(row, 0);
            //            ThongTinChiTietNhanKhau thongTinChiTietNhanKhau = new ThongTinChiTietNhanKhau(IdNhanKhau);
            //            thongTinChiTietNhanKhau.setVisible(true);
            //        }
    }//GEN-LAST:event_jTableGoiTapMouseClicked

    private void jTableGoiTapMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableGoiTapMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableGoiTapMouseEntered

    private void jTableGoiTapKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableGoiTapKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableGoiTapKeyPressed

    private void jButtonThemNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThemNhanVienActionPerformed
        // TODO add your handling code here:
        //        ThemNhanKhauView themNhanKhauView = new ThemNhanKhauView();
        //        themNhanKhauView.setVisible(true);
    }//GEN-LAST:event_jButtonThemNhanVienActionPerformed

    private void jButtonSuaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSuaNhanVienActionPerformed
        // TODO add your handling code here:
        //        TamVangView tamVangView = new TamVangView();
        //        tamVangView.setVisible(true);
    }//GEN-LAST:event_jButtonSuaNhanVienActionPerformed

    private void jButtonXoaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonXoaNhanVienActionPerformed
        // TODO add your handling code here:
        //        TamTruView tamTruView = new TamTruView();
        //        tamTruView.setVisible(true);
    }//GEN-LAST:event_jButtonXoaNhanVienActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSuaNhanVien;
    private javax.swing.JButton jButtonThemNhanVien;
    private javax.swing.JButton jButtonXoaNhanVien;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableGoiTap;
    // End of variables declaration//GEN-END:variables
}
