/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package quanlyphonggym.UI.HoiVienUI;

import quanlyphonggym.Bean.HoiVienBean;
import quanlyphonggym.Controllers.HoiVienCtrl.DangKyGoiTapCtrl;
import quanlyphonggym.Models.DangKyGoiTap;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;
import java.awt.*;
import java.sql.SQLException;
import java.util.EventObject;

/**
 *
 * @author nguyenduc
 */
public class DangKyGoiTapPanel extends javax.swing.JPanel {

    /**
     * Creates new form DangKyGoiTapPanel
     */
    public DangKyGoiTapPanel() {
        initComponents();
    }
    public DangKyGoiTapPanel(HoiVienBean hoiVienBean) throws SQLException, ClassNotFoundException {
        initComponents();
        HoiVienHomeUI.loadData();
        loadData(HoiVienHomeUI.hoiVienBean);
    }
    private static void loadData(HoiVienBean hoiVienBean2) {
        hoiVienBean = hoiVienBean2;
        if (hoiVienBean.getGoiTapHienTai().getGoiTap() != null) {

            jTextGoiTapHienTai.setText(hoiVienBean.getGoiTapHienTai().getGoiTap().getTenGoiTap());
            jTextNgayDangKy.setText(hoiVienBean.getGoiTapHienTai().getDangKyGoiTap().getNgayDangKy());
            jTextNgayBatDau.setText(hoiVienBean.getGoiTapHienTai().getDangKyGoiTap().getNgayBatDau());
            jTextNgayKetThuc.setText(hoiVienBean.getGoiTapHienTai().getDangKyGoiTap().getNgayKetThuc());
            jTextPTHuongDan.setText(hoiVienBean.getPT().getHoTen());
            jTextMaNhanVienPT.setText(hoiVienBean.getPT().getMaNhanVien());

            if (hoiVienBean.getGoiTapHienTai().getDangKyGoiTap().getTrangThaiThanhToan()) {
                jButtonThanhToan.setText("Đã thanh toán");
                jButtonThanhToan.setEnabled(true);
                jButtonThanhToan.setBackground(new Color(242, 242, 242));
            } else {
                jButtonThanhToan.setText("Chưa thanh toán");
                jButtonThanhToan.setEnabled(true);
                jButtonThanhToan.setBackground(new Color(242, 242, 242));
            }

        } else {
            jTextGoiTapHienTai.setText("Hội viên chưa đăng ký gói nào");
        }

        if (danhSachCacGoi.getRowCount()>0) danhSachCacGoi.setRowCount(0);
        for (int i = 0; i<hoiVienBean.getDanhSachGoiTapDaDangKy().size(); i++) {
            String tenGoi = hoiVienBean.getDanhSachGoiTapDaDangKy().get(i).getGoiTap().getTenGoiTap();
            String ngayDangKy = hoiVienBean.getDanhSachGoiTapDaDangKy().get(i).getDangKyGoiTap().getNgayDangKy();
            String ngayBatDau = hoiVienBean.getDanhSachGoiTapDaDangKy().get(i).getDangKyGoiTap().getNgayBatDau();
            String ngayKetThuc = hoiVienBean.getDanhSachGoiTapDaDangKy().get(i).getDangKyGoiTap().getNgayKetThuc();

            Object[] row = {tenGoi, ngayDangKy, ngayBatDau, ngayKetThuc};
            danhSachCacGoi.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableCacGoi = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextMaNhanVienPT = new javax.swing.JTextField();
        jTextPTHuongDan = new javax.swing.JTextField();
        jTextNgayKetThuc = new javax.swing.JTextField();
        jTextNgayBatDau = new javax.swing.JTextField();
        jTextNgayDangKy = new javax.swing.JTextField();
        jTextGoiTapHienTai = new javax.swing.JTextField();
        jButtonDangKy = new javax.swing.JButton();
        jButtonThanhToan = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel11.setText("Các gói tập đã đăng ký:");

        jTableCacGoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                    "Tên gói", "Ngày đăng kí", "Ngày bắt đầu", "Ngày kết thúc"
            }
        ));
        danhSachCacGoi = (DefaultTableModel) jTableCacGoi.getModel();
        TableCellEditor nonEditableCellEditor2 = new DefaultCellEditor(new JTextField()) {
            @Override
            public boolean isCellEditable(EventObject e) {
                return false;
            }
        };
        for (int column = 0; column < danhSachCacGoi.getColumnCount(); column++) {
            TableColumn tableColumn = jTableCacGoi.getColumnModel().getColumn(column);
            tableColumn.setCellEditor(nonEditableCellEditor2);
        }
        jTableCacGoi.setRowHeight(30);
        jTableCacGoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCacGoiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTableCacGoiMouseEntered(evt);
            }
        });
        jScrollPane3.setViewportView(jTableCacGoi);

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel10.setText("Gói tập hiện tại:");

        jLabel12.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel12.setText("Ngày đăng ký:");

        jLabel13.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel13.setText("Ngày bắt đầu:");

        jLabel14.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel14.setText("Ngày kết thúc:");

        jLabel15.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel15.setText("PT Hướng dẫn:");

        jLabel17.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel17.setText("Mã nhân viên PT:");

        jButtonDangKy.setBackground(new java.awt.Color(255, 255, 204));
        jButtonDangKy.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtonDangKy.setText("Đăng ký gói tập mới");
        jButtonDangKy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonDangKyActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jButtonThanhToan.setBackground(new java.awt.Color(255, 255, 204));
        jButtonThanhToan.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtonThanhToan.setText("Thanh toán");
        jButtonThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThanhToanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(59, 59, 59)
                                .addComponent(jTextMaNhanVienPT, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(jTextGoiTapHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextNgayDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(59, 59, 59)
                                .addComponent(jTextNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(59, 59, 59)
                                .addComponent(jTextPTHuongDan, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonDangKy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(272, 272, 272))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextGoiTapHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNgayDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextPTHuongDan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextMaNhanVienPT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableCacGoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCacGoiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableCacGoiMouseClicked

    private void jTableCacGoiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCacGoiMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTableCacGoiMouseEntered

    private void jButtonDangKyActionPerformed(java.awt.event.ActionEvent evt) throws SQLException, ClassNotFoundException {//GEN-FIRST:event_jButtonDangKyActionPerformed
        // TODO add your handling code here:
        DanhSachGoiTapJframe danhSachGoiTapJframe = new DanhSachGoiTapJframe();
        danhSachGoiTapJframe.setVisible(true);
    }//GEN-LAST:event_jButtonDangKyActionPerformed

    private void jButtonThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThanhToanActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButtonThanhToanActionPerformed

    public static boolean dangKyGoiTap(DangKyGoiTap dangKyGoiTap) throws SQLException, ClassNotFoundException {
        dangKyGoiTap.setIdHoiVien(hoiVienBean.getHoiVien().getId());

        DangKyGoiTapCtrl dangKyGoiTapCtrl = new DangKyGoiTapCtrl();
        if (dangKyGoiTapCtrl.dangKyGoiTap(dangKyGoiTap)) {
            JOptionPane.showMessageDialog(null, "Đăng ký thành công. Hãy thanh toán gói tập này");
            HoiVienHomeUI.loadData();
            loadData(HoiVienHomeUI.hoiVienBean);
            return true;
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDangKy;
    private static javax.swing.JButton jButtonThanhToan;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableCacGoi;
    private static javax.swing.JTextField jTextGoiTapHienTai;
    private static javax.swing.JTextField jTextMaNhanVienPT;
    private static javax.swing.JTextField jTextNgayBatDau;
    private static javax.swing.JTextField jTextNgayDangKy;
    private static javax.swing.JTextField jTextNgayKetThuc;
    private static javax.swing.JTextField jTextPTHuongDan;
    // End of variables declaration//GEN-END:variables
    private static HoiVienBean hoiVienBean;
    private static DefaultTableModel danhSachCacGoi;
}
