/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlyphonggym.UI.HoiVienUI;

import quanlyphonggym.Bean.HoiVienBean;
import quanlyphonggym.Controllers.AdminCtrl.QuanLyHoiVienCtrl.ChiTietHoiVienCtrl;
import quanlyphonggym.Controllers.HoiVienCtrl.HoiVienCtrl;
import quanlyphonggym.Models.HoiVien;

import java.awt.*;
import java.sql.SQLException;
import java.text.ParseException;

/**
 *
 * @author nguyenduc
 */
public class HoiVienHomeUI extends javax.swing.JFrame {

    /**
     * Creates new form HoiVienHomeUI
     */
    public HoiVienHomeUI() throws SQLException, ClassNotFoundException, ParseException {
        initComponents();
        setLocationRelativeTo(null);
        this.idHoiVien = 1;
        initComponents();
        setLocationRelativeTo(null);
        loadData();

        ThongTinHoiVienPanel thongTinHoiVienPanel = new ThongTinHoiVienPanel(this.hoiVienBean);
        ParentPanel.removeAll();
        ParentPanel.setLayout(new BorderLayout());
        ParentPanel.add(thongTinHoiVienPanel);
        ParentPanel.validate();
        ParentPanel.repaint();
    }
    public HoiVienHomeUI(int idHoiVien) throws SQLException, ClassNotFoundException, ParseException {
        this.idHoiVien = idHoiVien;
        initComponents();
        setLocationRelativeTo(null);
        loadData();
        ThongTinHoiVienPanel thongTinHoiVienPanel = new ThongTinHoiVienPanel(this.hoiVienBean);
        ParentPanel.removeAll();
        ParentPanel.setLayout(new BorderLayout());
        ParentPanel.add(thongTinHoiVienPanel);
        ParentPanel.validate();
        ParentPanel.repaint();
    }
    public  static void loadData() throws SQLException, ClassNotFoundException {
        ChiTietHoiVienCtrl chiTietHoiVienCtrl = new ChiTietHoiVienCtrl();
        hoiVienBean = chiTietHoiVienCtrl.getChiTietHoiVienById(idHoiVien);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonTrangChu = new javax.swing.JButton();
        jButtonLichSuTapLuyen = new javax.swing.JButton();
        jButtonDangKyGoiTap = new javax.swing.JButton();
        jButtonThanhToan = new javax.swing.JButton();
        ParentPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonTrangChu.setBackground(new java.awt.Color(255, 255, 204));
        jButtonTrangChu.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        jButtonTrangChu.setForeground(new java.awt.Color(102, 102, 255));
        jButtonTrangChu.setText("TRANG CHỦ");
        jButtonTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonTrangChuActionPerformed(evt);
                } catch (ParseException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jButtonLichSuTapLuyen.setBackground(new java.awt.Color(204, 255, 204));
        jButtonLichSuTapLuyen.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jButtonLichSuTapLuyen.setText("LỊCH SỬ TẬP LUYỆN");
        jButtonLichSuTapLuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLichSuTapLuyenActionPerformed(evt);
            }
        });

        jButtonDangKyGoiTap.setBackground(new java.awt.Color(204, 255, 204));
        jButtonDangKyGoiTap.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jButtonDangKyGoiTap.setText("ĐĂNG KÝ GÓI TẬP");
        jButtonDangKyGoiTap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonDangKyGoiTapActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jButtonThanhToan.setBackground(new java.awt.Color(204, 255, 204));
        jButtonThanhToan.setFont(new java.awt.Font("Liberation Sans", 1, 20)); // NOI18N
        jButtonThanhToan.setText("THANH TOÁN");
        jButtonThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonThanhToanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonDangKyGoiTap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonLichSuTapLuyen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButtonTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jButtonLichSuTapLuyen, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonDangKyGoiTap, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 467, Short.MAX_VALUE))
        );

        ParentPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout ParentPanelLayout = new javax.swing.GroupLayout(ParentPanel);
        ParentPanel.setLayout(ParentPanelLayout);
        ParentPanelLayout.setHorizontalGroup(
            ParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1105, Short.MAX_VALUE)
        );
        ParentPanelLayout.setVerticalGroup(
            ParentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ParentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ParentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTrangChuActionPerformed(java.awt.event.ActionEvent evt) throws ParseException {//GEN-FIRST:event_jButtonTrangChuActionPerformed
        // TODO add your handling code here:
                ThongTinHoiVienPanel thongTinHoiVienPanel = new ThongTinHoiVienPanel(hoiVienBean);
                ParentPanel.removeAll();
                ParentPanel.setLayout(new BorderLayout());
                ParentPanel.add(thongTinHoiVienPanel);
                ParentPanel.validate();
                ParentPanel.repaint();
    }//GEN-LAST:event_jButtonTrangChuActionPerformed

    private void jButtonLichSuTapLuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLichSuTapLuyenActionPerformed
        // TODO add your handling code here:
        LichSuTapLuyenPanel lichSuTapLuyenPanel = new LichSuTapLuyenPanel(hoiVienBean);
        ParentPanel.removeAll();
        ParentPanel.setLayout(new BorderLayout());
        ParentPanel.add(lichSuTapLuyenPanel);
        ParentPanel.validate();
        ParentPanel.repaint();
    }//GEN-LAST:event_jButtonLichSuTapLuyenActionPerformed

    private void jButtonDangKyGoiTapActionPerformed(java.awt.event.ActionEvent evt) throws SQLException, ClassNotFoundException {//GEN-FIRST:event_jButtonDangKyGoiTapActionPerformed
        // TODO add your handling code here:
        DangKyGoiTapPanel dangKyGoiTapPanel = new DangKyGoiTapPanel(hoiVienBean);
        ParentPanel.removeAll();
        ParentPanel.setLayout(new BorderLayout());
        ParentPanel.add(dangKyGoiTapPanel);
        ParentPanel.validate();
        ParentPanel.repaint();
    }//GEN-LAST:event_jButtonDangKyGoiTapActionPerformed

    private void jButtonThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonThanhToanActionPerformed
        // TODO add your handling code here:
        ThanhToanPanel thanhToanPanel = new ThanhToanPanel();
        ParentPanel.removeAll();
        ParentPanel.setLayout(new BorderLayout());
        ParentPanel.add(thanhToanPanel);
        ParentPanel.validate();
        ParentPanel.repaint();
    }//GEN-LAST:event_jButtonThanhToanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HoiVienHomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HoiVienHomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HoiVienHomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HoiVienHomeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new HoiVienHomeUI().setVisible(true);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                } catch (ParseException e) {
                    throw new RuntimeException(e);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ParentPanel;
    private javax.swing.JButton jButtonDangKyGoiTap;
    private javax.swing.JButton jButtonLichSuTapLuyen;
    private javax.swing.JButton jButtonThanhToan;
    private javax.swing.JButton jButtonTrangChu;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
    private static int idHoiVien;
    public static HoiVienBean hoiVienBean;
}
