/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package quanlyphonggym.UI.HoiVienUI;

import quanlyphonggym.Bean.HoiVienBean;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;
import java.util.EventObject;

/**
 *
 * @author nguyenduc
 */
public class LichSuTapLuyenPanel extends javax.swing.JPanel {

    /**
     * Creates new form LichSuTapLuyenPanel
     */
    public LichSuTapLuyenPanel() {
        initComponents();
    }

    public LichSuTapLuyenPanel(HoiVienBean hoiVienBean) {
        initComponents();

        loadData(HoiVienHomeUI.hoiVienBean);
    }
    private void loadData(HoiVienBean hoiVienBean) {
        this.hoiVienBean = hoiVienBean;
        if (danhSachLichSu.getRowCount()>0) danhSachLichSu.setRowCount(0);
        for (int i = 0; i<hoiVienBean.getLichSuSuDungDichVu().size(); i++) {
            String gioVao = hoiVienBean.getLichSuSuDungDichVu().get(i).getGioVao();
            String gioRa = hoiVienBean.getLichSuSuDungDichVu().get(i).getGioRa();
            String ngayTapLuyen = hoiVienBean.getLichSuSuDungDichVu().get(i).getNgaySuDung();

            Object[] row = {gioVao, gioRa, ngayTapLuyen};
            danhSachLichSu.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTableLichSu = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jTableLichSu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                    "Giờ vào", "Giờ ra", "Ngày tập luyện"
            }
        ));
        danhSachLichSu = (DefaultTableModel) jTableLichSu.getModel();
        TableCellEditor nonEditableCellEditor1 = new DefaultCellEditor(new JTextField()) {
            @Override
            public boolean isCellEditable(EventObject e) {
                return false;
            }
        };
        for (int column = 0; column < danhSachLichSu.getColumnCount(); column++) {
            TableColumn tableColumn = jTableLichSu.getColumnModel().getColumn(column);
            tableColumn.setCellEditor(nonEditableCellEditor1);
        }
        jTableLichSu.setRowHeight(30);
        jScrollPane2.setViewportView(jTableLichSu);

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel3.setText("Lịch sử sử dụng phòng tập:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(176, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addGap(122, 122, 122))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableLichSu;
    // End of variables declaration//GEN-END:variables
    private HoiVienBean hoiVienBean;
    private DefaultTableModel danhSachLichSu;
}
