/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package quanlyphonggym.UI.HoiVienUI;

import quanlyphonggym.Bean.NhanVienBean;
import quanlyphonggym.Bean.PhanHoiBean;
import quanlyphonggym.Controllers.AdminCtrl.QuanLyNhanVienCtrl.NhanVienCtrl;
import quanlyphonggym.Controllers.HoiVienCtrl.CRPhanHoiHoiVienCtrl;
import quanlyphonggym.Models.NhanVien;
import quanlyphonggym.Models.PhanHoiCuaHoiVien;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellEditor;
import javax.swing.table.TableColumn;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.EventObject;
import java.util.List;

/**
 *
 * @author nguyenduc
 */
public class PhanHoiPanel extends javax.swing.JPanel {
    private DefaultTableModel danhSachPhanHoi;
    private int idHoiVien;
    /**
     * Creates new form PhanHoiPanel
     */
    public PhanHoiPanel() throws SQLException, ClassNotFoundException {
        initComponents();
        loadData();
    }

    private void loadData() throws SQLException, ClassNotFoundException {
        HoiVienHomeUI.loadData();
        //load CombboxNhanVien
        jComboBox1.removeAllItems();
        List<NhanVienBean> nhanVienBeans = new ArrayList<>();
        NhanVienCtrl nhanVienCtrl = new NhanVienCtrl();
        nhanVienBeans = nhanVienCtrl.getAllNhanVien();
        for (int i = 0; i <nhanVienBeans.size(); i++) {
            String item = nhanVienBeans.get(i).getNhanVien().getId()+"-"+nhanVienBeans.get(i).getNhanVien().getHoTen()+"-"+nhanVienBeans.get(i).getRole().getTenRole();
            jComboBox1.addItem(item);
        }

        this.idHoiVien = HoiVienHomeUI.hoiVienBean.getHoiVien().getId();
        CRPhanHoiHoiVienCtrl crPhanHoiHoiVienCtrl = new CRPhanHoiHoiVienCtrl();
        List<PhanHoiBean> phanHoiBeanList  =crPhanHoiHoiVienCtrl.getAllPhanHoiCuaHoiVienById(idHoiVien);
//phanhoi
        if (danhSachPhanHoi.getRowCount()>0) danhSachPhanHoi.setRowCount(0);
        for (int i = 0; i<phanHoiBeanList.size(); i++) {
            int id = phanHoiBeanList.get(i).getPhanHoiCuaHoiVien().getId();
            int idNhanVien = phanHoiBeanList.get(i).getPhanHoiCuaHoiVien().getIdNhanVien();
            String yKienHoiVien = phanHoiBeanList.get(i).getPhanHoiCuaHoiVien().getNoiDung();
            String traLoi = null;
            String check = "Chưa trả lời";
            String ngayPhanHoi = phanHoiBeanList.get(i).getPhanHoiCuaHoiVien().getNgayPhanHoi();

            if (phanHoiBeanList.get(i).getPhanHoiCuaHoiVien().getIsDaPhanHoiLai()) {
                traLoi = phanHoiBeanList.get(i).getPhanHoiCuaAdmin().getNoiDung();
                check = "đã trả lời";
            }

            Object[] row = {id, idNhanVien, yKienHoiVien, traLoi, check, ngayPhanHoi};
            danhSachPhanHoi.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaYKien = new javax.swing.JTextArea();
        jButtonGui = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setText("Chọn nhân viên cần phản hồi:");

        jTextAreaYKien.setColumns(20);
        jTextAreaYKien.setRows(5);
        jScrollPane1.setViewportView(jTextAreaYKien);

        jButtonGui.setBackground(new java.awt.Color(255, 255, 102));
        jButtonGui.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jButtonGui.setText("Gửi");
        jButtonGui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonGuiActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jComboBox1.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable1.setFont(new java.awt.Font("Liberation Sans", 0, 16)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
                new String [] {
                        "ID", "ID Nhân viên", "Ý kiến hội viên", "Trả lời", "Check", "Ngày phản hồi"
                }
        ));

        danhSachPhanHoi = (DefaultTableModel) jTable1.getModel();
        TableCellEditor non = new DefaultCellEditor(new JTextField()) {
            @Override
            public boolean isCellEditable(EventObject e) {
                return false;
            }
        };
        for (int column = 0; column < danhSachPhanHoi.getColumnCount(); column++) {
            TableColumn tableColumn = jTable1.getColumnModel().getColumn(column);
            tableColumn.setCellEditor(non);
        }
        jTable1.setRowHeight(30);
        jScrollPane2.setViewportView(jTable1);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        jLabel2.setText("Danh sách ý kiến phản hồi:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 829, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(38, 38, 38)
                            .addComponent(jButtonGui, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(201, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGui, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 85, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGuiActionPerformed(java.awt.event.ActionEvent evt) throws SQLException, ClassNotFoundException {//GEN-FIRST:event_jButtonGuiActionPerformed
        // TODO add your handling code here:
        if (jTextAreaYKien.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Hãy nhập ý kiến phản hồi");
            return;
        }
        PhanHoiCuaHoiVien phanHoiCuaHoiVien = new PhanHoiCuaHoiVien();
        phanHoiCuaHoiVien.setIdHoiVien(idHoiVien);

        String str = (String) jComboBox1.getSelectedItem();
        String[] part = str.split("-");
        int idNhanVien = Integer.parseInt(part[0].trim());

        phanHoiCuaHoiVien.setIdNhanVien(idNhanVien);
        phanHoiCuaHoiVien.setNoiDung(jTextAreaYKien.getText());

        CRPhanHoiHoiVienCtrl crPhanHoiHoiVienCtrl = new CRPhanHoiHoiVienCtrl();
        if (crPhanHoiHoiVienCtrl.guiPhanHoi(phanHoiCuaHoiVien)) {
            loadData();
        }

    }//GEN-LAST:event_jButtonGuiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGui;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextAreaYKien;
    // End of variables declaration//GEN-END:variables
}
