/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package quanlyphonggym.UI.HoiVienUI;

import quanlyphonggym.Bean.HoiVienBean;
import quanlyphonggym.Controllers.HoiVienCtrl.HoiVienCtrl;
import quanlyphonggym.Models.HoiVien;
import quanlyphonggym.Util.DateForm;

import javax.swing.*;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 *
 * @author nguyenduc
 */
public class ThongTinHoiVienPanel extends javax.swing.JPanel {

    /**
     * Creates new form ThongTinHoiVienPanel
     */
    public ThongTinHoiVienPanel() {
        initComponents();
    }
    public ThongTinHoiVienPanel(HoiVienBean hoiVienBean) throws ParseException {
        initComponents();

        loadData(HoiVienHomeUI.hoiVienBean);
        jButtonLuuThongTin.setEnabled(false);
    }
    private void loadHoiVien(HoiVien hoiVien) throws ParseException {

    }
    private void loadData(HoiVienBean hoiVienBean2) throws ParseException {
        this.hoiVienBean = hoiVienBean2;
        jTextIdHocVien.setText(String.valueOf(hoiVienBean.getHoiVien().getId()));
        jTextMaHocVien.setText(hoiVienBean.getHoiVien().getMaHoiVien());
        jTextHoTen.setText(hoiVienBean.getHoiVien().getHoTen());
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date date = dateFormat.parse(hoiVienBean.getHoiVien().getNgaySinh());
        jDateChooser1.setDate(date);
        jTextGioiTinh.setText(hoiVienBean.getHoiVien().getGioiTinh());
        jTextDiaChi.setText(hoiVienBean.getHoiVien().getDiaChi());
        jTextSoDienThoai.setText(hoiVienBean.getHoiVien().getSoDienThoai());
        if (hoiVienBean.getGoiTapHienTai().getGoiTap() != null) {

            jTextGoiTapHienTai.setText(hoiVienBean.getGoiTapHienTai().getGoiTap().getTenGoiTap());
            jTextNgayDangKy.setText(hoiVienBean.getGoiTapHienTai().getDangKyGoiTap().getNgayDangKy());
            jTextNgayBatDau.setText(hoiVienBean.getGoiTapHienTai().getDangKyGoiTap().getNgayBatDau());
            jTextNgayKetThuc.setText(hoiVienBean.getGoiTapHienTai().getDangKyGoiTap().getNgayKetThuc());
            jTextPTHuongDan.setText(hoiVienBean.getPT().getHoTen());
            jTextMaNhanVienPT.setText(hoiVienBean.getPT().getMaNhanVien());
        } else {
            jTextGoiTapHienTai.setText("Hội viên chưa đăng ký gói nào");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextSoDienThoai = new javax.swing.JTextField();
        jTextDiaChi = new javax.swing.JTextField();
        jTextGioiTinh = new javax.swing.JTextField();
        jTextHoTen = new javax.swing.JTextField();
        jTextMaHocVien = new javax.swing.JTextField();
        jTextIdHocVien = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextGoiTapHienTai = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextNgayDangKy = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextNgayBatDau = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextNgayKetThuc = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextPTHuongDan = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextMaNhanVienPT = new javax.swing.JTextField();
        jButtonChinhSua = new javax.swing.JButton();
        jButtonLuuThongTin = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel1.setText("ID Học viên:");

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel4.setText("Mã Học viên:");

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel5.setText("Họ tên:");

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel6.setText("Ngày sinh:");

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel7.setText("Giới tính:");

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel2.setText("Địa chỉ:");

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel8.setText("Số điện thoại:");

        jTextSoDienThoai.setEditable(false);
        jTextSoDienThoai.setBackground(new java.awt.Color(255, 255, 255));

        jTextDiaChi.setEditable(false);
        jTextDiaChi.setBackground(new java.awt.Color(255, 255, 255));

        jTextGioiTinh.setEditable(false);
        jTextGioiTinh.setBackground(new java.awt.Color(255, 255, 255));

        jTextHoTen.setEditable(false);
        jTextHoTen.setBackground(new java.awt.Color(255, 255, 255));

        jTextMaHocVien.setEditable(false);
        jTextMaHocVien.setBackground(new java.awt.Color(255, 255, 255));

        jTextIdHocVien.setEditable(false);
        jTextIdHocVien.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel10.setText("Gói tập hiện tại:");

        jTextGoiTapHienTai.setEditable(false);
        jTextGoiTapHienTai.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel12.setText("Ngày đăng ký:");

        jTextNgayDangKy.setEditable(false);
        jTextNgayDangKy.setBackground(new java.awt.Color(255, 255, 255));

        jLabel13.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel13.setText("Ngày bắt đầu:");

        jTextNgayBatDau.setEditable(false);
        jTextNgayBatDau.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel14.setText("Ngày kết thúc:");

        jTextNgayKetThuc.setEditable(false);
        jTextNgayKetThuc.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel15.setText("PT Hướng dẫn:");

        jTextPTHuongDan.setEditable(false);
        jTextPTHuongDan.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel17.setText("Mã nhân viên PT:");

        jTextMaNhanVienPT.setEditable(false);
        jTextMaNhanVienPT.setBackground(new java.awt.Color(255, 255, 255));

        jButtonChinhSua.setBackground(new java.awt.Color(255, 255, 204));
        jButtonChinhSua.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtonChinhSua.setText("Chỉnh sửa thông tin");
        jButtonChinhSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChinhSuaActionPerformed(evt);
            }
        });

        jButtonLuuThongTin.setBackground(new java.awt.Color(255, 255, 204));
        jButtonLuuThongTin.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jButtonLuuThongTin.setText("Lưu thông tin");
        jButtonLuuThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    jButtonLuuThongTinActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                } catch (ClassNotFoundException e) {
                    throw new RuntimeException(e);
                } catch (ParseException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jDateChooser1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonChinhSua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLuuThongTin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextDiaChi, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(jTextSoDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(jTextGioiTinh, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(jTextHoTen, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(jTextIdHocVien, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(jTextMaHocVien, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextMaNhanVienPT, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextNgayDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextPTHuongDan, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextGoiTapHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextGoiTapHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextNgayDangKy, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextPTHuongDan, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextMaNhanVienPT, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextIdHocVien, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextMaHocVien, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addComponent(jButtonChinhSua, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonLuuThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonChinhSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChinhSuaActionPerformed
        // TODO add your handling code here:
        jTextMaHocVien.setEditable(true);
        jTextMaHocVien.requestFocus();
        jTextHoTen.setEditable(true);
        jTextGioiTinh.setEditable(true);
        jTextDiaChi.setEditable(true);
        jTextSoDienThoai.setEditable(true);
        jButtonLuuThongTin.setEnabled(true);
    }//GEN-LAST:event_jButtonChinhSuaActionPerformed

    private void jButtonLuuThongTinActionPerformed(java.awt.event.ActionEvent evt) throws SQLException, ClassNotFoundException, ParseException {//GEN-FIRST:event_jButtonLuuThongTinActionPerformed
        // TODO add your handling code here:
        if (jTextMaHocVien.getText().isEmpty()
        || jTextHoTen.getText().isEmpty()
        || jTextGioiTinh.getText().isEmpty()
        || jTextDiaChi.getText().isEmpty()
        || jTextSoDienThoai.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Hãy nhập đầy đủ thông tin");
            return;
        }
        HoiVien hoiVien = new HoiVien();
        hoiVien.setId(hoiVienBean.getHoiVien().getId());
        hoiVien.setMaHoiVien(jTextMaHocVien.getText());
        hoiVien.setHoTen(jTextHoTen.getText());
        hoiVien.setNgaySinh(DateForm.returnDateString(jDateChooser1.getDate()));
        hoiVien.setGioiTinh(jTextGioiTinh.getText());
        hoiVien.setDiaChi(jTextDiaChi.getText());
        hoiVien.setSoDienThoai(jTextSoDienThoai.getText());

        HoiVienCtrl hoiVienCtrl = new HoiVienCtrl();
        if (hoiVienCtrl.updateThongTinCaNhan(hoiVien)) {
            JOptionPane.showMessageDialog(null, "Đã cập nhật");
            HoiVienHomeUI.loadData();
            loadData(HoiVienHomeUI.hoiVienBean);
            jTextMaHocVien.setEditable(false);
            jTextHoTen.setEditable(false);
            jTextGioiTinh.setEditable(false);
            jTextDiaChi.setEditable(false);
            jTextSoDienThoai.setEditable(false);
            jButtonLuuThongTin.setEnabled(false);
            return;
        }

    }//GEN-LAST:event_jButtonLuuThongTinActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonChinhSua;
    private javax.swing.JButton jButtonLuuThongTin;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextDiaChi;
    private javax.swing.JTextField jTextGioiTinh;
    private javax.swing.JTextField jTextGoiTapHienTai;
    private javax.swing.JTextField jTextHoTen;
    private javax.swing.JTextField jTextIdHocVien;
    private javax.swing.JTextField jTextMaHocVien;
    private javax.swing.JTextField jTextMaNhanVienPT;
    private javax.swing.JTextField jTextNgayBatDau;
    private javax.swing.JTextField jTextNgayDangKy;
    private javax.swing.JTextField jTextNgayKetThuc;
    private javax.swing.JTextField jTextPTHuongDan;
    private javax.swing.JTextField jTextSoDienThoai;
    // End of variables declaration//GEN-END:variables
    private HoiVienBean hoiVienBean;
}
